# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./scripts:/docker-entrypoint-initdb.d/"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
